# https://github.com/leftwm/leftwm/wiki/Config#togglefloating
modkey = "Mod4" # Super
mousekey = "Mod4"

focus_behaviour = "Sloppy" # Can be Sloppy, ClickTo, or Driven
focus_new_windows = true
sloppy_mouse_follows_focus = false # Only active with the Sloppy behaviour
disable_tile_drag = true

tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
workspaces = []
# layout_mode = "Workspace"
layout_mode = "Tag"
layouts = [
    "GridHorizontal",
    "MainAndVertStack",
    # "MainAndHorizontalStack",
    "MainAndDeck",
    # "EvenHorizontal",
    # "EvenVertical",
    # "Fibonacci",
    # "CenterMain",
    # "CenterMainBalanced",
    "Monocle",
    # "RightWiderLeftStack",
    # "LeftWiderRightStack",
]

window_rules = [
  # games in 4
  {window_class = "Steam", spawn_on_tag = 4 },
  {window_class = "Lutris", spawn_on_tag = 4 },
  {window_class = "battle.net.exe", spawn_on_tag = 4 },
  # windows whose window title is "Pentablet" will be spawned floating on tag 9
  # {window_title = "Pentablet", spawn_on_tag = 9, spawn_floating = true},
]

# Create a scratchpad for alacritty
[[scratchpad]]
name = "Alacritty" # This is the name which is referenced when calling (case-sensitive)
value = "alacritty" # The command to load the application if it isn't started
# x, y, width, height are in pixels when an integer is inputted or a percentage when a float is inputted.
# These values are relative to the size of the workspace, and will be restricted depending on the workspace size.
x = 0.25
y = 0.25
height = 0.50
width = 0.50

# https://github.com/leftwm/leftwm/blob/main/leftwm-core/src/utils/xkeysym_lookup.rs#L46

#[[keybind]]
#command = "ToggleScratchPad"
#value = "Alacritty" # Name set for the scratchpad
#modifier = ["modkey"]
#key = "p"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "SetLayout"
value = "Monocle"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "SetLayout"
value = "GridHorizontal"
modifier = ["modkey", "Shift"]
key = "m"
    
[[keybind]]
command = "ToggleSticky"
modifier = ["modkey"]
key = "v"

[[keybind]]
command = "ToggleFloating"
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "Execute"
value = "~/.bin/rofi_quicklinks.sh"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "rofi -show window"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "Execute"
value = "rofi -show combi"
modifier = ["modkey"]
key = "o"

[[keybind]]
command = "Execute"
value = "~/.bin/rofi_open_pdf.sh"
modifier = ["modkey", "Shift"]
key = "o"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "SoftReload"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Control"]
key = "b"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "Execute"
value = "xscreensaver"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "period"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey"]
key = "comma"

[[keybind]]
command = "RotateTag"
modifier = ["modkey"]
key = "z"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"

[[keybind]]
command = "Execute"
value = "~/.bin/maim_save.sh"
modifier = ["modkey"]
key = "Print"

[[keybind]]
command = "Execute"
value = "~/.bin/maim_clip.sh"
modifier = []
key = "Print"

[[keybind]]
command = "Execute"
value = "amixer -q set Master 5%- unmute"
modifier = []
key = "XF86XK_AudioLowerVolume"

[[keybind]]
command = "Execute"
value = "amixer -q set Master 5%+ unmute"
modifier = []
key = "XF86XK_AudioRaiseVolume"

[[keybind]]
command = "Execute"
value = "amixer -q set Master toggle"
modifier = []
key = "XF86XK_AudioMute"
