
[greenclip]
  blacklisted_applications = []
  enable_image_support = true
  history_file = "/home/di/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 50
  max_selection_size_bytes = 0
  static_history = ["Let's think step by step to make sure you have the correct answer."]
  trim_space_from_selection = true
  use_primary_selection_as_input = false
