theme = "onedark"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
auto-pairs = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
ret = ["open_below", "normal_mode"]

[keys.insert]
j = { j = "normal_mode"}


